# Generated by Django 6.0.7 on 2026-07-14 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_branch_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='contry',
            new_name='country',
        ),
    ]
