# Generated by Django 6.0.7 on 2026-07-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_contry_company_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='cui',
            field=models.CharField(max_length=15),
        ),
    ]
