# Generated by Django 6.0.7 on 2026-07-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_collaborator_cui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='cui',
            field=models.CharField(max_length=13),
        ),
    ]
